In [1]:
import geopandas as gpd
import shapely.geometry
from shapely import wkt
import pandas as pd
import ast
from shapely.ops import unary_union
from shapely.geometry import MultiPolygon, Polygon
from shapely.validation import make_valid
import json
import os

In [51]:
reamining_fields = pd.read_csv("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/LR/final_Data_for_voronoi/data_for_voronoi/final_ord_remanining_with_&_without_crop_4_voronoi.csv")
reamining_fields['geometry'] = reamining_fields['geometry'].apply(wkt.loads)
reamining_fields = gpd.GeoDataFrame(reamining_fields)
reamining_fields = reamining_fields.set_crs(27700, allow_override=True)
reamining_fields

,Unnamed: 0,fid,primary_ke,calculated,Area(hec),geometry,lucode,cromeid,Crom_area_lap,max_lucode_occurance,crop_maxA
0,0,osgb5000005221327933,3.366578e+10,1088.761590,0.108968,"POLYGON ((475455.975 487901.126, 475447.98 487...",NaN,NaN,NaN,NaN,NaN
1,1,osgb1000000129942037,7.728228e+10,34063.852518,3.409737,"POLYGON ((400772.8 259408, 400761.997 259388.8...","['Grass', 'Grass', 'Spring Barley', 'Spring Ba...","['RPA400606259553', 'RPA400786259518', 'RPA400...","[0.25441316897373567, 0.2841763214855901, 0.40...",9.0,Grass
2,2,osgb1000000403587006,2.965524e+10,18807.910574,1.880313,"POLYGON ((175815.976 29873.588, 175805.922 298...",NaN,NaN,NaN,NaN,NaN
3,3,osgb5000005206600819,2.574438e+10,16579.973953,1.659481,"POLYGON ((460370.64 321960.5, 460345.27 321963...","['Spring Wheat', 'Spring Linseed', 'Spring Whe...","['RPA460366321977', 'RPA460246321977', 'RPA460...","[0.22669729160895094, 0.0301790511289904, 0.39...",3.0,Spring Wheat
4,4,osgb1000000226166812,2.452981e+10,10080.154000,1.009002,"POLYGON ((384105.08 457641.35, 384117.21 45764...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1746451,1746451,osgb1000000102632283,2.543826e+10,5763.292480,0.576896,"POLYGON ((406327.37 379863.57, 406329.24 37986...","['Grass', 'Clover', 'Trees and Scrubs, short W...","['RPA406306379792', 'RPA406366379827', 'RPA406...","[0.29261316204947524, 0.14882970664822903, 0.0...",2.0,Grass
1746452,1746452,osgb5000005244372010,8.019583e+10,1892.277586,0.189406,"POLYGON ((440925.501 165501.165, 440928.46 165...","['Winter Wheat', 'Grass', 'Clover']","['RPA440926165538', 'RPA440986165503', 'RPA440...","[0.15374573603189204, 0.0017862773116623584, 0...",1.0,Winter Wheat
1746453,1746453,osgb5000005247635093,5.326630e+10,13915.511145,1.392677,"POLYGON ((484111.584 227877.872, 484119.983 22...","['Winter Oats', 'Lucerne', 'Winter Oats', 'Win...","['RPA484186228065', 'RPA484246227961', 'RPA484...","[0.11948479593374248, 0.22246115959131985, 0.3...",3.0,Winter Oats
1746454,1746454,osgb1000000180925952,7.295428e+10,35889.525063,3.591842,"POLYGON ((314345.67 528614.012, 314348.183 528...","['Winter Field beans', 'Grass', 'Grass', 'Luce...","['RPA314326528714', 'RPA314206528575', 'RPA314...","[7.691240638573836e-05, 0.41, 0.13793570847855...",3.0,Grass
1746455,1746455,osgb1000000328907172,6.028019e+10,43755.218701,4.378680,"POLYGON ((297030.1 123981.1, 297024.4 123955.8...","['Winter Wheat', 'Grass', 'Winter Wheat']","['RPA296986124211', 'RPA296866124003', 'RPA296...","[0.34228221432059913, 0.26128936577124895, 0.41]",2.0,Winter Wheat

In [50]:
farms = gpd.read_file("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/LR/final_Data_for_voronoi/voronoi_polygon_without_dummy/voronoi_region_without_dummy.gpkg")
farms

,ID,farm_name,New_full_a,Full Post,Partial Po,Place type,new_lat,new_lon,Cattle,Goats,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,geometry
0,FARM24791,HILLSIDE FARM,"NEWTON RD, ISLES OF SCILLY, TR23 0PR, UNITED K...",TR23 0PR,0PR,Farm,49.9524,-6.3552,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((25177.225 229271.616, 26791.31 22730..."
1,FARM54516,TROYTOWN FARM,"ISLES OF SCILLY, TR22 0PL, UNITED KINGDOM",TR22 0PL,0PL,Farm,49.8915,-6.3515,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((25177.225 -63228.744, 25177.225 1269..."
2,FARM51538,TAMARISK FARM,"TAMARISK FARM, ST AGNES, ISLES OF SCILLY, TR...",TR22 0PL,0PL,Agricultural producers,49.9139,-6.3191,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,"POLYGON ((88783.511 12631.908, 89596.796 12676..."
3,FARM47449,SCILLY ORGANICS,"SCILLY ORGANICS, MIDDLE TOWN, ST MARTINS, ISLE...",TR25 0QN,0QN,Agricultural producers,49.9663,-6.2957,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,"POLYGON ((26791.31 227305.061, 30413.433 22298..."
4,FARM05058,BORO FARM,"BOROUGH FARM, ISLES OF SCILLY, TR24 0PX, UNITE...",TR24 0PX,0PX,Farm,49.9537,-6.3261,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((88707.279 19510.873, 91407.039 14722..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61485,FARM45965,ROE'S FARM,"CORTON, LOWESTOFT, NR32 5LG, UNITED KINGDOM",NR32 5LG,5LG,Farm,52.5277,1.7346,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((653621.897 300672.993, 659734.515 30..."
61486,FARM59332,WOBURN FARM,"CORTON, LOWESTOFT, NR32 5LE, UNITED KINGDOM",NR32 5LE,5LE,Farm,52.5216,1.7348,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((653344.351 298410.022, 660767.294 29..."
61487,FARM07393,BURTON V C,"PARKHILL, LOWESTOFT, NR32 5DQ, UNITED KINGDOM",NR32 5DQ,5DQ,Farm,52.4988,1.7226,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652426.933 295055.59, 653139.473 296..."
61488,FARM51693,TAYLORS FARM,"CORTON, LOWESTOFT, NR32 5NJ, UNITED KINGDOM",NR32 5NJ,5NJ,Farm,52.5142,1.7263,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652492.862 296992.498, 652814.759 29..."
61489,FARM08203,CARPENTERS SHOP FARM,"CARPENTERS SHOP FARM, CARPENTERS SHOP FARM, BL...",NR32 5PP,5PP,None,52.5089,1.7261,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652783.622 296926.124, 654285.03 296..."

In [37]:
data = ['Petrol Service Stations', 'Skip Hire', 'Boat and Yacht Moorings', 'Horse Transportation Services', 'Social Welfare Services', 'English Restaurant', 'French Restaurant', 'Wine Merchants', 'Car Park Operators', 'Ice Cream Manufacture', 'Bakers', 'Greengrocers', 'Vets', 'Fencing Contractors', 'Rehearsal Studios', 'Waste Disposal', 'Landscape Contractors', 'Function Rooms, Halls and Banqueting Facilities', 'Mobile Home Parks', 'Car Accessories and Parts', 'Storage and Warehousing Facilities', 'Straw Merchants', 'Horse Trainers', 'Nursing Homes', 'Educational Services', 'Property Owners', 'Christmas Goods', 'Florists', 'Entertainments', 'Telemarketing Services & Call Centres', 'Container Hire and Transportation', 'Restaurants', 'Pub Food Restaurant', 'Food Packers', 'Pick Your Own Fruit and Vegetables', 'Firewood Suppliers', 'Business Centre Management', 'Window Cleaners', 'Conference Centres and Facilities', 'Housing Associations and Trusts', 'Courier Services', 'Parks and Gardens', 'Fireplaces', 'Dog Breeders', 'Radio and Television Production Services', 'Blacksmiths', 'Carpenters and Joiners', 'Nurserymen', 'Sheltered Housing Accommodation', 'Furniture Designers', 'Bakers & Bread Manufacture', 'Community Centres', 'Car Body Repairers', 'Wedding Venues - Civil', 'Caravan Storage', 'Gardeners', 'Builders', 'Camping Equipment Supplies', 'Supermarkets', 'Retirement Homes', 'Agricultural Consultants', 'Roofing Consultants', 'Antique Dealers', 'Corporate Entertainment and Hospitality', 'Fishing and Angling Clubs', 'Poultry Dealers and Wholesalers', 'Model Shops', 'Community Networks', 'Art Galleries & Dealers', 'Catteries', 'Boiler Manufacturers', 'Furniture Stores', 'Fishermen', 'Research Laboratories', 'Firework Shop', 'Serviced Office Facilities', 'Cider Makers', 'Zoos', 'E-commerce', 'Car Servicing and Repair', 'Agricultural Engineering', 'Bacon Curers', 'Digital Services', 'Construction Contractors', 'Beauty Salons', 'Delicatessens', 'Pub and Restaurant Management', 'Wedding Services', 'Caterers', 'Internet Service Providers', 'Veterinary Products Manufacture', 'Fence and Gate Suppliers', 'Catering Schools', 'Convenience Stores', 'Colleges', 'Estate Agents', 'Joinery Manufacture', 'Agricultural Machinery', 'Salvage Dealers', 'Schools', 'Saddlers and Equestrian Kits', 'Health Food Shops', 'Cheese Makers', 'Charity Shops', 'Land Developers', 'Cabinet Makers', 'Office Premises Retail', 'Cake Makers', 'Doctors', 'Kitchen Planners and Fitters', 'Boat Hire', 'Durable Goods Wholesalers', 'Special Schools', 'Religious Organisations', 'Frozen Food Wholesale', 'Catering & Food Consultants', 'Accountants', 'Nurseries Wholesale', 'Pottery and Ceramics Manufacture', 'Plumbers', 'Turf Growers, Suppliers and Contractors', 'Furniture Restoration', 'Sports Coaching', 'Soft Drinks Manufacturers', 'Grocers and General Stores', 'Glassware Manufacture', 'Tour and Holiday Operators', 'Training', 'Leisure Centres', 'Woodworking Supplies', 'Sound, Recording and Rehearsal Studios', 'Post Offices', 'Nursery Schools', 'Aquarium and Pond Suppliers', 'Frozen Food Processors', 'Apartment Buildings', 'Pet Shops', 'Entertainment Centres', 'Groundwork Contractors', 'Car Dealers', 'Picture Framing Services', 'Sand and Gravel Wholesale', 'Machine Tool Manufacture', 'Food Manufacture', 'Removals', 'Fruit Juice Producers', 'Takeaways', 'Day Centres', 'Letting Agents', 'General Manufacturers', 'Bricklayers', 'Meals on Wheels', 'Boat Moorings', 'Florists Wholesale', 'Haulage Contractors', 'Industrial Units', 'Marketing Consultants', 'Chiropodists', 'Gardening Designers', 'Agricultural Buildings', 'Computer Software Development', 'Office Rental', 'Animal By-Products', 'Archive Storage', 'Seed Merchants', 'Frozen Food Shops', 'Accommodation Booking Agencies', 'Herbs and Spices Suppliers and Retailers', 'Unisex Hairdressers', 'Landscape Designers', 'Medical Equipment Supply', 'Caravan Dealers', 'Childminders', 'Riding Wear and Equestrian Supplies', 'Manufacturers Agents', 'Electricians & Electrical Contractors', 'Estate Management Services', 'Pizza Delivery', 'Hardware Stores and Ironmongers', 'Timber Merchants', 'Pet Services', 'Potato Merchants', 'Childcare Services', 'Chemists', 'Automated Gates Manufacturer', 'Health and Medical Clinics', 'Reclamation Centres', 'Metal Manufacture', 'Mushroom Growers', 'Wholesale of Machinery and Equipment', 'Brewers', 'Public Swimming Pools', 'Woodburning Stoves', 'Harbours and Ports Operators', 'Golf Clubs and Courses', 'Animal Welfare Societies', 'Functions - Hire Services', 'Bee Keepers', 'Cladding Suppliers and Contractors', 'Surveyors', 'Herb Growers', 'MOT Testing', 'Places of Worship', 'Drinks - Delivered', 'Property Developers', 'Refrigeration Equipment', 'Publishing of Magazines and Newspapers', 'Directories', 'Rehabilitation Centres', 'Health Clubs & Fitness Centres', 'Caravans Repair and Servicing', 'Residential Property Developers', 'Sightseeing Tours and Trips', 'Double Glazing', 'Home Help and Carers', 'Indian Restaurant', 'Foundation Schools', 'Lawnmowers and Garden Machinery', 'Animal Transportation Services', 'Marquee Hire', 'Recycling', 'Dog Obedience Trainers', 'Insurance Brokers', 'Embroidery Specialists', 'Curtains', 'Wine from Grapes', 'Meat Products', 'Other Wholesale', 'Forestry Advisers', 'Art Gallery', 'Web Design', 'Plant Hire', 'Outdoor Leisure Pursuit Organisers', 'Distilleries', 'Fishery Consultants', 'Museums and Art Galleries', 'Bedroom Furniture Manufacture', 'Video Production, Filming and Copying', 'Herbalists', 'Confectionery Retail', 'Night Clubs', 'Sports Clubs', 'Sports and Social Clubs', 'Toy Shops', 'Creches', 'Import and Export Agents', 'Holding Companies', 'Courts', 'Industrial Cleaners', 'Market Gardeners', 'Property and Building Maintenance', 'Catalogue and Home Shopping', 'Domestic Waste Disposal Units', 'Computer Systems and Software Sales', 'Catering Supplies Wholesale', 'Childrens Play Groups & Play Schools', 'Cleaning Equipment Wholesale', 'Motorbike and Scooters Retail', 'Horse Drawn Carriage Hire', 'Fish and Chip Shops', 'Concrete Contractors', 'Manufacture and Supply of Wooden Containers', 'Landscape Gardening', 'Physiotherapists', 'Independent Schools', 'Clay Pigeon Shoots and Rifle Ranges', 'Local Government', 'Mental Health Services', 'Visitor Centres', 'Cash and Carry', 'Water Treatment Services', 'Motorbike and Scooter Manufacture', 'Market Research', 'Driving Instructors','Charities and Trusts','Holiday Homes and Self-Catering Accommodation','Guest Houses','Riding Schools, Stables and Equestrian Centres','Camp Sites','Mechanics','Business Information Services','Outdoor Clothing and Equipment Shops','Bed & Breakfasts','Agricultural Merchants','Hostels','Hotels','Cafes and Coffee Shops','Fruit and Vegetable Wholesale','Agricultural Contractors','NHS Clinics', 'Electrical Domestic Appliance Repair',
       'Electrical Domestic Appliance Wholesale','Dentists', 'Business Transfer Agents', 'Fashion Shops',
       'Libraries', 'Adult Education Centre', 'Cookers Sales and Service',
       'Gift Services', 'Distribution Services',
       'Fabricated Metal Products', 
       'Mechanical Engineering',
       'Residential Care Establishments', 'Photographers',
       'Sixth Form Colleges', 'Entertainment Agencies and Organisers',
'Bulb Growers and Suppliers', 'Pubs','Horticultural Services',
'Land Agencies',
       'Nutritionists', 'Livery Companies', 'Business Consultants',
       'Craft Centres & Shops', 'Home Staging',
       "Children's Activity Playcentres", 'Holiday Parks and Villages','Caravan Parks', 'Business Services', 'Disability Services',
       'Confectionery Manufacture','Animal Feed and Pet Foods',
       'Agricultural Contractors', 'Arts Centres',
       'Garden Centres & Nurseries', 'Kennels', 'Bird Of Prey Centre',
       'Tourist Attractions','Produce Merchants','Farm Shops']

In [38]:
farms = farms[~farms['Place type'].isin(list(data))]
farms

,ID,farm_name,New_full_a,Full Post,Partial Po,Place type,new_lat,new_lon,Cattle,Goats,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,geometry
0,FARM00001,Lower Mynthurst Farm,"LOWER MYNTHURST FARM, HORLEY, RH6 0HR, UNITED ...",RH6 0HR,0HR,Farm,51.1873,-0.2326,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (523611.873 144603.809)
1,FARM00002,Bailey Hill Farm,"BAILEY HILL FARM, AMERSHAM RD, CHALFONT ST GIL...",HP8 4RT,4RT,Farm,51.6430,-0.5739,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (498775.227 194762.352)
2,FARM00003,MILL END,"OXFORD RD, ROCKWELL END, MILL END, HENLEY-ON-T...",RG9 6NF,6NF,Farm,51.5576,-0.8660,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (478711.273 184910.638)
3,FARM00004,. RAW MILK DUMELOWSDAIRY,"THE GABLES FARM MAIN STREET, CALKE, LEICESTER,...",LE65 1RR,1RR,Dairy farm,52.7945,-1.4487,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (437271 322021.956)
4,FARM00005,MILL FIELD FARM,"MILL FIELD FARM, MILL LANE, NEWARK, NG23 6AJ, ...",NG23 6AJ,6AJ,Farm,53.1361,-0.8926,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (474182.169 360452.959)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64078,FARM64079,ONLEY GROUNDS FARM SHOP,"ONLEY GROUNDS FARM, WILLOUGHBY, RUGBY, WARWICK...",CV23 8AJ,8AJ,Meat Wholesalers,52.3319,-1.2571,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (450719.735 270681.216)
64089,FARM64090,ZOES FARM,"HUNGERFORD, RG17 7TR, UNITED KINGDOM",RG17 7TR,7TR,Farm,51.4888,-1.5714,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (429854.036 176737.131)
64112,FARM64113,ZUSS,"RECTORY LN, LATCHINGDON, CHELMSFORD CM3 6HB, U...",CM3 6HB,6HB,Farm,51.6592,0.7267,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (588691.487 199121.307)
64120,FARM64121,MANOR FARM BUTCHERS LTD,"BURCOMBE LANE, BURCOMBE, SALISBURY, WILTSHIRE,...",SP2 0EJ,0EJ,Butchers,51.0773,-1.8991,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (407164.423 130891.809)
64121,FARM64122,MOUNT FARM,"MOUNT FARM, SHAVES WOOD LN, ALBOURNE, HASSOCKS...",BN6 9DX,9DX,Farm,50.9251,-0.2238,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (524929.837 115462.996)

In [45]:
farms['Place type'].unique()

array(['Farm', 'Dairy farm', 'Egg supplier', None,
       'Agricultural producers', 'Livestock Farming', 'Poultry farm',
       'Cattle farm', 'Livestock breeder', 'Organic farm',
       'Livestock producer', 'Livestock Breeders', 'Organic Food',
       'Eggs Wholesale', 'Dairy Farmers', 'Poultry Farmers',
       'Horse Breeders', 'Dairies', 'Dairy Produce Merchants',
       'Mixed Farming', 'Butterfly Farm', 'Arable Farming', 'Stud Farms',
       'Fish Farms', 'Butchers', 'Meat Wholesalers',
       'Fruit and Vegetable Growers', 'Poultry and Game Breeders'],
      dtype=object)

In [42]:
number_width = len(str(len(farms)))

# Generate the IDs with leading zeros
farms['ID'] = ['FARM' + str(i).zfill(number_width) for i in range(1, len(farms) + 1)]
farms

/Users/smit0225/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,ID,farm_name,New_full_a,Full Post,Partial Po,Place type,new_lat,new_lon,Cattle,Goats,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,geometry
0,FARM00001,Lower Mynthurst Farm,"LOWER MYNTHURST FARM, HORLEY, RH6 0HR, UNITED ...",RH6 0HR,0HR,Farm,51.1873,-0.2326,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (523611.873 144603.809)
1,FARM00002,Bailey Hill Farm,"BAILEY HILL FARM, AMERSHAM RD, CHALFONT ST GIL...",HP8 4RT,4RT,Farm,51.6430,-0.5739,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (498775.227 194762.352)
2,FARM00003,MILL END,"OXFORD RD, ROCKWELL END, MILL END, HENLEY-ON-T...",RG9 6NF,6NF,Farm,51.5576,-0.8660,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (478711.273 184910.638)
3,FARM00004,. RAW MILK DUMELOWSDAIRY,"THE GABLES FARM MAIN STREET, CALKE, LEICESTER,...",LE65 1RR,1RR,Dairy farm,52.7945,-1.4487,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (437271 322021.956)
4,FARM00005,MILL FIELD FARM,"MILL FIELD FARM, MILL LANE, NEWARK, NG23 6AJ, ...",NG23 6AJ,6AJ,Farm,53.1361,-0.8926,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (474182.169 360452.959)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64078,FARM61486,ONLEY GROUNDS FARM SHOP,"ONLEY GROUNDS FARM, WILLOUGHBY, RUGBY, WARWICK...",CV23 8AJ,8AJ,Meat Wholesalers,52.3319,-1.2571,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (450719.735 270681.216)
64089,FARM61487,ZOES FARM,"HUNGERFORD, RG17 7TR, UNITED KINGDOM",RG17 7TR,7TR,Farm,51.4888,-1.5714,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (429854.036 176737.131)
64112,FARM61488,ZUSS,"RECTORY LN, LATCHINGDON, CHELMSFORD CM3 6HB, U...",CM3 6HB,6HB,Farm,51.6592,0.7267,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (588691.487 199121.307)
64120,FARM61489,MANOR FARM BUTCHERS LTD,"BURCOMBE LANE, BURCOMBE, SALISBURY, WILTSHIRE,...",SP2 0EJ,0EJ,Butchers,51.0773,-1.8991,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (407164.423 130891.809)
64121,FARM61490,MOUNT FARM,"MOUNT FARM, SHAVES WOOD LN, ALBOURNE, HASSOCKS...",BN6 9DX,9DX,Farm,50.9251,-0.2238,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTIPOINT (524929.837 115462.996)

In [43]:
farms = gpd.GeoDataFrame(farms)
farms = farms.set_crs('epsg:27700')
farms.to_file("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/LR/final_Data_for_voronoi/voronoi_fram_without_dummy/voronoi_frams_without_dummy.gpkg",driver='GPKG')

In [37]:
farms

,ID,farm_name,New_full_a,Full Post,Partial Po,Place type,new_lat,new_lon,Cattle,Goats,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,geometry
0,FARM62371,TROYTOWN FARM,TENT ONLY FAMILY-RUN CAMPSITE ON SMALL ISLAND....,None,None,Camp Sites,49.8702,-6.4006,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((26819.554 -59119.817, 26819.554 3544..."
1,FARM24791,HILLSIDE FARM,"NEWTON RD, ISLES OF SCILLY, TR23 0PR, UNITED K...",TR23 0PR,0PR,Farm,49.9524,-6.3552,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((26819.554 227210.272, 88707.279 1951..."
2,FARM54517,TROYTOWN FARM,"ISLES OF SCILLY, TR22 0PL, UNITED KINGDOM",TR22 0PL,0PL,Farm,49.8915,-6.3515,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((124758.648 -59119.817, 83065.321 115..."
3,FARM46980,SALAKEE FARM,"SALAKEE, ISLES OF SCILLY, TR21 0NZ, UNITED KIN...",TR21 0NZ,0NZ,Farm,49.9163,-6.2904,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((127566.258 -59119.817, 111664.781 -3..."
4,FARM63664,VERONICA FARM FUDGE,"VERONICA FARM, BRYHER, ISLES OF SCILLY, TR23 0PR",TR23 0PR,0PR,Confectionery Retail,49.9507,-6.3533,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((82864.466 11676.995, 88752.585 15422..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64120,FARM59806,WOODLANDS FARM,"CORTON, LOWESTOFT, NR32 5NH, UNITED KINGDOM",NR32 5NH,5NH,Farm,52.5165,1.7262,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652850.226 297952.514, 653456.199 29..."
64121,FARM59333,WOBURN FARM,"CORTON, LOWESTOFT, NR32 5LE, UNITED KINGDOM",NR32 5LE,5LE,Farm,52.5216,1.7348,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((653344.351 298410.022, 660767.294 29..."
64122,FARM07393,BURTON V C,"PARKHILL, LOWESTOFT, NR32 5DQ, UNITED KINGDOM",NR32 5DQ,5DQ,Farm,52.4988,1.7226,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652426.933 295055.59, 653139.473 296..."
64123,FARM51694,TAYLORS FARM,"CORTON, LOWESTOFT, NR32 5NJ, UNITED KINGDOM",NR32 5NJ,5NJ,Farm,52.5142,1.7263,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652492.862 296992.498, 652814.759 29..."
64124,FARM08203,CARPENTERS SHOP FARM,"CARPENTERS SHOP FARM, CARPENTERS SHOP FARM, BL...",NR32 5PP,5PP,None,52.5089,1.7261,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((652783.622 296926.124, 654285.03 296..."

In [57]:
a = gpd.sjoin(reamining_fields,farms, predicate='intersects')
a = a.reset_index(drop=True)
a

,fid,primary_ke,calculated,lucode,cromeid,Crom_area_lap,max_lucode_occurance,crop_maxA,Area(hec),geometry,...,Pigs,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables
0,osgb5000005221327933,3.366578e+10,1088.761590,NaN,NaN,NaN,NaN,NaN,0.108968,"POLYGON ((475455.975 487901.126, 475447.98 487...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,osgb1000000129942037,7.728228e+10,34063.852518,"['Grass', 'Grass', 'Spring Barley', 'Spring Ba...","['RPA400606259553', 'RPA400786259518', 'RPA400...","[0.25441316897373567, 0.2841763214855901, 0.40...",9.0,Grass,3.409737,"POLYGON ((400772.8 259408, 400761.997 259388.8...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,osgb1000000403587006,2.965524e+10,18807.910574,NaN,NaN,NaN,NaN,NaN,1.880313,"POLYGON ((175815.976 29873.588, 175805.922 298...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,osgb5000005206600819,2.574438e+10,16579.973953,"['Spring Wheat', 'Spring Linseed', 'Spring Whe...","['RPA460366321977', 'RPA460246321977', 'RPA460...","[0.22669729160895094, 0.0301790511289904, 0.39...",3.0,Spring Wheat,1.659481,"POLYGON ((460370.64 321960.5, 460345.27 321963...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,osgb5000005206600819,2.574438e+10,16579.973953,"['Spring Wheat', 'Spring Linseed', 'Spring Whe...","['RPA460366321977', 'RPA460246321977', 'RPA460...","[0.22669729160895094, 0.0301790511289904, 0.39...",3.0,Spring Wheat,1.659481,"POLYGON ((460370.64 321960.5, 460345.27 321963...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231898,osgb5000005244372010,8.019583e+10,1892.277586,"['Winter Wheat', 'Grass', 'Clover']","['RPA440926165538', 'RPA440986165503', 'RPA440...","[0.15374573603189204, 0.0017862773116623584, 0...",1.0,Winter Wheat,0.189406,"POLYGON ((440925.501 165501.165, 440928.46 165...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2231899,osgb5000005247635093,5.326630e+10,13915.511145,"['Winter Oats', 'Lucerne', 'Winter Oats', 'Win...","['RPA484186228065', 'RPA484246227961', 'RPA484...","[0.11948479593374248, 0.22246115959131985, 0.3...",3.0,Winter Oats,1.392677,"POLYGON ((484111.584 227877.872, 484119.983 22...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2231900,osgb1000000180925952,7.295428e+10,35889.525063,"['Winter Field beans', 'Grass', 'Grass', 'Luce...","['RPA314326528714', 'RPA314206528575', 'RPA314...","[7.691240638573836e-05, 0.41, 0.13793570847855...",3.0,Grass,3.591842,"POLYGON ((314345.67 528614.012, 314348.183 528...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2231901,osgb1000000180925952,7.295428e+10,35889.525063,"['Winter Field beans', 'Grass', 'Grass', 'Luce...","['RPA314326528714', 'RPA314206528575', 'RPA314...","[7.691240638573836e-05, 0.41, 0.13793570847855...",3.0,Grass,3.591842,"POLYGON ((314345.67 528614.012, 314348.183 528...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2231902,osgb1000000328907172,6.028019e+10,43755.218701,"['Winter Wheat', 'Grass', 'Winter Wheat']","['RPA296986124211', 'RPA296866124003', 'RPA296...","[0.34228221432059913, 0.26128936577124895, 0.41]",2.0,Winter Wheat,4.378680,"POLYGON ((297030.1 123981.1, 297024.4 123955.8...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
a.columns

Index(['Unnamed: 0', 'fid', 'primary_ke', 'calculated', 'Area(hec)',
       'geometry', 'lucode', 'cromeid', 'Crom_area_lap',
       'max_lucode_occurance', 'crop_maxA', 'index_right', 'ID', 'farm_name',
       'New_full_a', 'Full Post', 'Partial Po', 'Place type', 'new_lat',
       'new_lon', 'Cattle', 'Goats', 'Other Live', 'Pigs', 'Poultry', 'Sheep',
       'Cereals', 'Fruit & nu', 'Herbs & Or', 'Other crop', 'Permanent',
       'Temporary', 'Vegetables'],
      dtype='object')

In [58]:

geo_idx = 0
for idx, col_n in enumerate(a.columns):
    if col_n=='geometry':
        geo_idx = idx
# Apply this to the geometries that might be invalid
a['geometry'] = a['geometry'].apply(lambda geom: make_valid(geom) if not geom.is_valid else geom)
farms['geometry'] = farms['geometry'].apply(lambda geom: make_valid(geom) if not geom.is_valid else geom)

a['V_O_area_prc'] = a.apply(lambda row: (row[geo_idx].intersection(farms.iloc[row[geo_idx+1]].geometry).area / row[geo_idx].area) * 100, axis=1)
a = a.reset_index(drop=True)

/var/folders/px/16g77p5171d2dplxlk6vn8_h0000gr/T/ipykernel_11161/2259950223.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a['V_O_area_prc'] = a.apply(lambda row: (row[geo_idx].intersection(farms.iloc[row[geo_idx+1]].geometry).area / row[geo_idx].area) * 100, axis=1)

In [59]:
a

,fid,primary_ke,calculated,lucode,cromeid,Crom_area_lap,max_lucode_occurance,crop_maxA,Area(hec),geometry,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,V_O_area_prc
0,osgb5000005221327933,3.366578e+10,1088.761590,NaN,NaN,NaN,NaN,NaN,0.108968,"POLYGON ((475455.975 487901.126, 475447.98 487...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1,osgb1000000129942037,7.728228e+10,34063.852518,"['Grass', 'Grass', 'Spring Barley', 'Spring Ba...","['RPA400606259553', 'RPA400786259518', 'RPA400...","[0.25441316897373567, 0.2841763214855901, 0.40...",9.0,Grass,3.409737,"POLYGON ((400772.8 259408, 400761.997 259388.8...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
2,osgb1000000403587006,2.965524e+10,18807.910574,NaN,NaN,NaN,NaN,NaN,1.880313,"POLYGON ((175815.976 29873.588, 175805.922 298...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
3,osgb5000005206600819,2.574438e+10,16579.973953,"['Spring Wheat', 'Spring Linseed', 'Spring Whe...","['RPA460366321977', 'RPA460246321977', 'RPA460...","[0.22669729160895094, 0.0301790511289904, 0.39...",3.0,Spring Wheat,1.659481,"POLYGON ((460370.64 321960.5, 460345.27 321963...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.384796
4,osgb5000005206600819,2.574438e+10,16579.973953,"['Spring Wheat', 'Spring Linseed', 'Spring Whe...","['RPA460366321977', 'RPA460246321977', 'RPA460...","[0.22669729160895094, 0.0301790511289904, 0.39...",3.0,Spring Wheat,1.659481,"POLYGON ((460370.64 321960.5, 460345.27 321963...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.615204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231898,osgb5000005244372010,8.019583e+10,1892.277586,"['Winter Wheat', 'Grass', 'Clover']","['RPA440926165538', 'RPA440986165503', 'RPA440...","[0.15374573603189204, 0.0017862773116623584, 0...",1.0,Winter Wheat,0.189406,"POLYGON ((440925.501 165501.165, 440928.46 165...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
2231899,osgb5000005247635093,5.326630e+10,13915.511145,"['Winter Oats', 'Lucerne', 'Winter Oats', 'Win...","['RPA484186228065', 'RPA484246227961', 'RPA484...","[0.11948479593374248, 0.22246115959131985, 0.3...",3.0,Winter Oats,1.392677,"POLYGON ((484111.584 227877.872, 484119.983 22...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
2231900,osgb1000000180925952,7.295428e+10,35889.525063,"['Winter Field beans', 'Grass', 'Grass', 'Luce...","['RPA314326528714', 'RPA314206528575', 'RPA314...","[7.691240638573836e-05, 0.41, 0.13793570847855...",3.0,Grass,3.591842,"POLYGON ((314345.67 528614.012, 314348.183 528...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.291199
2231901,osgb1000000180925952,7.295428e+10,35889.525063,"['Winter Field beans', 'Grass', 'Grass', 'Luce...","['RPA314326528714', 'RPA314206528575', 'RPA314...","[7.691240638573836e-05, 0.41, 0.13793570847855...",3.0,Grass,3.591842,"POLYGON ((314345.67 528614.012, 314348.183 528...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.708801
2231902,osgb1000000328907172,6.028019e+10,43755.218701,"['Winter Wheat', 'Grass', 'Winter Wheat']","['RPA296986124211', 'RPA296866124003', 'RPA296...","[0.34228221432059913, 0.26128936577124895, 0.41]",2.0,Winter Wheat,4.378680,"POLYGON ((297030.1 123981.1, 297024.4 123955.8...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000

In [60]:
idx = a.groupby('fid')['V_O_area_prc'].idxmax()
final_data = a.loc[idx]
final_data = final_data.reset_index(drop=True)
final_data

,fid,primary_ke,calculated,lucode,cromeid,Crom_area_lap,max_lucode_occurance,crop_maxA,Area(hec),geometry,...,Poultry,Sheep,Cereals,Fruit & nu,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,V_O_area_prc
0,osgb1000000003000442,2.634589e+10,16021.021349,"['Grass', 'Lucerne']","['RPA601966301192', 'RPA601906301157']","[0.41, 0.16916221517850694]",1.0,Grass,1.602073,"POLYGON ((602029.29 301183.85, 602032.08 30117...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1,osgb1000000003000471,4.673119e+10,12044.726249,"['Winter Oilseed', 'Lucerne']","['RPA601786301157', 'RPA601906301157']","[0.09568223941103388, 0.08315439547114745]",1.0,Winter Oilseed,1.204452,"POLYGON ((601896.58 301175.91, 601898.06 30117...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.222696
2,osgb1000000003000477,4.673142e+10,34519.895901,"['Winter Barley', 'Winter Oilseed', 'Grass', '...","['RPA601606301053', 'RPA601786301157', 'RPA601...","[0.02087073281263409, 0.06684406935046966, 0.4...",1.0,Grass,3.451938,"POLYGON ((601736.271 301303.63, 601736.88 3012...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.880177
3,osgb1000000003000501,4.673227e+10,20208.105249,"['Trees and Scrubs, short Woody plants, hedger...",['RPA600826301919'],[0.015628439607740793],1.0,"Trees and Scrubs, short Woody plants, hedgerows",2.020795,"POLYGON ((600962.52 301904.47, 600947.613 3018...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.443366
4,osgb1000000003000519,2.634553e+10,249982.343872,"['Winter Wheat', 'Beet', 'Beet', 'Beet', 'Spri...","['RPA602326300846', 'RPA602086300568', 'RPA602...","[2.8437595928122132e-05, 0.13753200232964474, ...",13.0,Beet,24.997758,"POLYGON ((601824.48 300517.47, 601816.41 30051...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.450943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746451,osgb5000005296656689,8.442517e+10,6723.793296,['Non agriculture land'],['RPA415246103669'],[0.09313327829291068],1.0,Non agriculture land,0.673036,"POLYGON ((415334.176 103593.36, 415332.097 103...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1746452,osgb5000005296658301,8.416386e+10,8566.355360,['Winter Field beans'],['RPA362926491786'],[0.11840719119393733],1.0,Winter Field beans,0.857451,"POLYGON ((362853.536 491674.627, 362848.754 49...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1746453,osgb5000005296662587,8.442640e+10,3433.438230,"['Winter Field beans', 'Winter Field beans', '...","['RPA417046106856', 'RPA417046106925', 'RPA416...","[0.1701188734569757, 0.12064909397741597, 0.03...",2.0,Winter Field beans,0.343679,"POLYGON ((417020.618 106841.001, 417011.159 10...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1746454,osgb5000005296665457,8.442656e+10,1197.340695,NaN,NaN,NaN,NaN,NaN,0.119851,"POLYGON ((415122.192 109403.244, 415162.284 10...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
1746455,osgb5000005296665903,8.416501e+10,1479.524145,NaN,NaN,NaN,NaN,NaN,0.148094,"POLYGON ((366533.39 472925.05, 366532.89 47292...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000

In [62]:
final_data = final_data[['ID', 'farm_name', 'New_full_a', 'Full Post','fid', 'primary_ke', 'calculated', 'lucode', 'cromeid', 'Crom_area_lap',
       'max_lucode_occurance', 
        
       'Partial Po', 'Place type', 'Herbs & Or', 'Other crop', 'Permanent',
       'Temporary', 'Vegetables', 'crop_maxA', 'Area(hec)', 'geometry']]
final_data

,ID,farm_name,New_full_a,Full Post,fid,primary_ke,calculated,lucode,cromeid,Crom_area_lap,...,Partial Po,Place type,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,crop_maxA,Area(hec),geometry
0,FARM36749,MONEY HILL FARM,"MONEY HILL FARM, MONEY HILL FARM, DEOPHAM ROAD...",NR9 4NL,osgb1000000003000442,2.634589e+10,16021.021349,"['Grass', 'Lucerne']","['RPA601966301192', 'RPA601906301157']","[0.41, 0.16916221517850694]",...,4NL,None,NaN,NaN,NaN,NaN,NaN,Grass,1.602073,"POLYGON ((602029.29 301183.85, 602032.08 30117..."
1,FARM36749,MONEY HILL FARM,"MONEY HILL FARM, MONEY HILL FARM, DEOPHAM ROAD...",NR9 4NL,osgb1000000003000471,4.673119e+10,12044.726249,"['Winter Oilseed', 'Lucerne']","['RPA601786301157', 'RPA601906301157']","[0.09568223941103388, 0.08315439547114745]",...,4NL,None,NaN,NaN,NaN,NaN,NaN,Winter Oilseed,1.204452,"POLYGON ((601896.58 301175.91, 601898.06 30117..."
2,FARM17942,FROST ROW FARM,"UNNAMED ROAD, NORWICH, HINGHAM, UNITED KINGDOM",None,osgb1000000003000477,4.673142e+10,34519.895901,"['Winter Barley', 'Winter Oilseed', 'Grass', '...","['RPA601606301053', 'RPA601786301157', 'RPA601...","[0.02087073281263409, 0.06684406935046966, 0.4...",...,None,Poultry farm,NaN,NaN,NaN,NaN,NaN,Grass,3.451938,"POLYGON ((601736.271 301303.63, 601736.88 3012..."
3,FARM34777,MANSON GREEN FARM,"MANSON GREEN FARM, MANSON GREEN FARM, HIGHAM, ...",NR9 4PX,osgb1000000003000501,4.673227e+10,20208.105249,"['Trees and Scrubs, short Woody plants, hedger...",['RPA600826301919'],[0.015628439607740793],...,4PX,None,NaN,NaN,NaN,NaN,NaN,"Trees and Scrubs, short Woody plants, hedgerows",2.020795,"POLYGON ((600962.52 301904.47, 600947.613 3018..."
4,FARM09165,CHESTNUT FARM,"CHESTNUT FARM, CHESTNUT FARM, MONEY HILL, HING...",NR9 4NJ,osgb1000000003000519,2.634553e+10,249982.343872,"['Winter Wheat', 'Beet', 'Beet', 'Beet', 'Spri...","['RPA602326300846', 'RPA602086300568', 'RPA602...","[2.8437595928122132e-05, 0.13753200232964474, ...",...,4NJ,None,NaN,NaN,NaN,NaN,NaN,Beet,24.997758,"POLYGON ((601824.48 300517.47, 601816.41 30051..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746451,FARM17523,FOUR ACRE FARM,"LONG LN, RINGWOOD, BH24 3BX, UNITED KINGDOM",BH24 3BX,osgb5000005296656689,8.442517e+10,6723.793296,['Non agriculture land'],['RPA415246103669'],[0.09313327829291068],...,3BX,Farm,NaN,NaN,NaN,NaN,NaN,Non agriculture land,0.673036,"POLYGON ((415334.176 103593.36, 415332.097 103..."
1746452,FARM44090,R & JM HARPER,"HEBBLETHWAITE MARTHWAITE, SEDBERGH, LA10 5HW, ...",LA10 5HW,osgb5000005296658301,8.416386e+10,8566.355360,['Winter Field beans'],['RPA362926491786'],[0.11840719119393733],...,5HW,Farm,NaN,NaN,NaN,NaN,NaN,Winter Field beans,0.857451,"POLYGON ((362853.536 491674.627, 362848.754 49..."
1746453,FARM00251,"3, PADGET RD","3 PADGET RD, RINGWOOD BH24 1TE, UK",BH24 1TE,osgb5000005296662587,8.442640e+10,3433.438230,"['Winter Field beans', 'Winter Field beans', '...","['RPA417046106856', 'RPA417046106925', 'RPA416...","[0.1701188734569757, 0.12064909397741597, 0.03...",...,1TE,None,NaN,NaN,NaN,NaN,NaN,Winter Field beans,0.343679,"POLYGON ((417020.618 106841.001, 417011.159 10..."
1746454,FARM36676,MOCKBEGGAR FARM,"4 CROSS LANES, MOCKBEGGAR, RINGWOOD BH24 3NQ, ...",BH24 3NQ,osgb5000005296665457,8.442656e+10,1197.340695,NaN,NaN,NaN,...,3NQ,Farm,NaN,NaN,NaN,NaN,NaN,NaN,0.119851,"POLYGON ((415122.192 109403.244, 415162.284 10..."
1746455,FARM32983,LOWFIELD FARM,"LOWFIELD FARM, LOWFIELD FARM, CARNFORTH, LA6 3...",LA6 3LB,osgb5000005296665903,8.416501e+10,1479.524145,NaN,NaN,NaN,...,3LB,None,NaN,NaN,NaN,NaN,NaN,NaN,0.148094,"POLYGON ((366533.39 472925.05, 366532.89 47292..."

In [115]:
final_data[final_data['crop_maxA'].isna()]

,ID,farm_name,New_full_a,Full Post,fid,primary_ke,calculated,lucode,cromeid,Crom_area_lap,...,Place type,Herbs & Or,Other crop,Permanent,Temporary,Vegetables,V_O_area_prc,crop_maxA,Area(hec),geometry
10,FARM034777,MANSON GREEN FARM,"MANSON GREEN FARM, MANSON GREEN FARM, HIGHAM, ...",NR9 4PX,osgb1000000003003518,4.673222e+10,7141.115748,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.714103,"POLYGON ((601343.73 303265.87, 601337.23 30326..."
13,FARM034778,MANSON GREEN FARM,"MANSON GREEN FARM, MANSON GREEN FARM MANSON GR...",NR9 4PY,osgb1000000003003528,7.404134e+10,14789.158827,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,1.478900,"POLYGON ((601354.38 303862.73, 601336.96 30386..."
15,FARM034778,MANSON GREEN FARM,"MANSON GREEN FARM, MANSON GREEN FARM MANSON GR...",NR9 4PY,osgb1000000003003558,2.634569e+10,3080.889664,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.308086,"POLYGON ((600993.25 303815.4, 600991.29 303818..."
17,FARM034778,MANSON GREEN FARM,"MANSON GREEN FARM, MANSON GREEN FARM MANSON GR...",NR9 4PY,osgb1000000003003576,2.634541e+10,599.068755,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.059906,"POLYGON ((601135.968 303846.915, 601136.309 30..."
28,FARM089277,DUMMY25154,None,None,osgb1000000003004163,2.634576e+10,2886.084017,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.288603,"POLYGON ((601957.317 304864.622, 601957.238 30..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746432,FARM013261,DEANS BIGGIN FARM MANSERGH,"DEANS BIGGIN FARM MANSERGH, DEANS BIGGIN FARM ...",LA6 2EL,osgb5000005296654999,8.416302e+10,5463.045836,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.546822,"POLYGON ((360558.35 481466.12, 360552.33 48147..."
1746438,FARM070612,DUMMY6487,None,None,osgb5000005296665457,8.442656e+10,1197.340695,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,73.174276,NaN,0.119851,"POLYGON ((415122.192 109403.244, 415162.284 10..."
1746439,FARM032983,LOWFIELD FARM,"LOWFIELD FARM, LOWFIELD FARM, CARNFORTH, LA6 3...",LA6 3LB,osgb5000005296665903,8.416501e+10,1479.524145,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,0.148094,"POLYGON ((366533.39 472925.05, 366532.89 47292..."
1746445,FARM035005,MARSHALL MEADOWS FARM,"MARSHALL MEADOWS FARM, MARSHALL MEADOWS FARM, ...",TD15 1UT,osgb5000005234238789,7.472059e+10,925.125143,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.092604,"POLYGON ((397894.637 656806.618, 397873.862 65..."
1746454,FARM035005,MARSHALL MEADOWS FARM,"MARSHALL MEADOWS FARM, MARSHALL MEADOWS FARM, ...",TD15 1UT,osgb5000005118353043,2.734070e+10,39289.008740,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.932777,"POLYGON ((397124.069 656812.869, 397118.72 656..."

In [73]:
final_data = final_data.reset_index(drop=True)
final_data = gpd.GeoDataFrame(final_data)
final_data = final_data.set_crs('epsg:27700')
final_data.to_csv("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/final_database/without cluster/final_data_voronoi_without_dummy/final_after_Applying_voronoi_without_dummy.csv")

In [ ]:
final_data.to_file("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/final_database/fina_data_voronoi/final_after_Applying_voronoi.shp")

/var/folders/px/16g77p5171d2dplxlk6vn8_h0000gr/T/ipykernel_14463/1349486063.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  final_data.to_file("/Users/smit0225/Documents/Oxford/Agriculture/Land_Registry/filtered_fields/new_defra_data/final_database/fina_data_voronoi/final_after_Applying_voronoi.shp")